var card1 = Card(color: Color.Coeur, value: Value.As)
var card2 = Card(color: Color.Pique, value: Value.Valet)
print (card1.description)
print (card2.description)
print (card1 == card2)
card1 = Card(color: Color.Coeur, value: Value.As)
card2 = Card(color: Color.Coeur, value: Value.As)
print (card1.description)
print (card2.description)
print (card1 == card2)